version: '3'
services:
  ec-suite:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: nodemon server.js
