FROM node:18.16.0
ENV TZ=Asia/Tokyo
WORKDIR /app
COPY package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \ 
    then npm install; \ 
    else npm install --only=production; \
    fi
EXPOSE $PORT
COPY . ./
CMD ["node", "server.js"]
